//
// E:/Copy achugh89@gmail.com/15618/Project/15618_Project/src/scene/hit_ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_E__COPY_ACHUGH89_GMAIL_COM_15618_PROJECT_15618_PROJECT_SRC_SCENE_HIT_ISPC_H
#define ISPC_E__COPY_ACHUGH89_GMAIL_COM_15618_PROJECT_15618_PROJECT_SRC_SCENE_HIT_ISPC_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_E__COPY_ACHUGH89_GMAIL_COM_15618_PROJECT_15618_PROJECT_SRC_SCENE_HIT_ISPC_H
