//
// /afs/andrew.cmu.edu/usr5/abhishec/15618/15618_Project/src/scene/hit_ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC__AFS_ANDREW_CMU_EDU_USR5_ABHISHEC_15618_15618_PROJECT_SRC_SCENE_HIT_ISPC_H
#define ISPC__AFS_ANDREW_CMU_EDU_USR5_ABHISHEC_15618_15618_PROJECT_SRC_SCENE_HIT_ISPC_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
extern "C" {
#endif // __cplusplus
    extern int32_t hit(float * e_x, float * e_y, float * e_z, float * dir_x, float * dir_y, float * dir_z, float t0, float t1, double * lowCoord, double * highCoord, int32_t start, int32_t end, int32_t fullRecord, int8_t * result);
    extern int32_t hitLast(float * e_x, float * e_y, float * e_z, float * dir_x, float * dir_y, float * dir_z, float t0, float t1, double * lowCoord, double * highCoord, int32_t start, int32_t end);
    extern void hit_triangle(float * e_x, float * e_y, float * e_z, float * dir_x, float * dir_y, float * dir_z, double t0, double * t1, double * v0, double * v1, double * v2, const double invMat[][4], int32_t start, int32_t end, int32_t fullRecord, int32_t * hit_flag, float * texCoord_x, float * texCoord_y, float * norm_x, float * norm_y, float * norm_z);
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC__AFS_ANDREW_CMU_EDU_USR5_ABHISHEC_15618_15618_PROJECT_SRC_SCENE_HIT_ISPC_H
