//
// /afs/andrew.cmu.edu/usr1/chenxil/Documents/15618_Project/src/scene/partition_ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC__AFS_ANDREW_CMU_EDU_USR1_CHENXIL_DOCUMENTS_15618_PROJECT_SRC_SCENE_PARTITION_ISPC_H
#define ISPC__AFS_ANDREW_CMU_EDU_USR1_CHENXIL_DOCUMENTS_15618_PROJECT_SRC_SCENE_PARTITION_ISPC_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC__AFS_ANDREW_CMU_EDU_USR1_CHENXIL_DOCUMENTS_15618_PROJECT_SRC_SCENE_PARTITION_ISPC_H
