//
// E:/Copy achugh89@gmail.com/15618/Project/15618_Project/src/scene/partition_ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_E__COPY_ACHUGH89_GMAIL_COM_15618_PROJECT_15618_PROJECT_SRC_SCENE_PARTITION_ISPC_H
#define ISPC_E__COPY_ACHUGH89_GMAIL_COM_15618_PROJECT_15618_PROJECT_SRC_SCENE_PARTITION_ISPC_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus
///////////////////////////////////////////////////////////////////////////
// Vector types with external visibility from ispc code
///////////////////////////////////////////////////////////////////////////

#ifndef __ISPC_VECTOR_float3__
#define __ISPC_VECTOR_float3__
#ifdef _MSC_VER
__declspec( align(16) ) struct float3 { float v[3]; };
#else
struct float3 { float v[3]; } __attribute__ ((aligned(16)));
#endif
#endif


#ifndef __ISPC_STRUCT_BVHPrimitiveInfo__
#define __ISPC_STRUCT_BVHPrimitiveInfo__
struct BVHPrimitiveInfo {
    int32_t primitiveNumber;
    float3  centroid;
    float3  lowCoord;
    float3  highCoord;
};
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
extern "C" {
#endif // __cplusplus
    extern void hashBuckets(int32_t start, int32_t end, struct BVHPrimitiveInfo * buildData, int32_t nBuckets);
    extern int32_t partition_ispc(int32_t start, int32_t end, int32_t dim, float mid, struct BVHPrimitiveInfo * buildData, struct BVHPrimitiveInfo * result);
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_E__COPY_ACHUGH89_GMAIL_COM_15618_PROJECT_15618_PROJECT_SRC_SCENE_PARTITION_ISPC_H
